import React, { useState, useEffect } from 'react';
import { QrReader } from 'react-qr-reader';

// Main App component for MediVerify
function App() {
  // State to store the scanned QR code data
    const [scanResult, setScanResult] = useState('');
      // State to manage the camera facing mode (user or environment)
        const [facingMode, setFacingMode] = useState('environment'); // 'environment' for back camera, 'user' for front camera
          // State to display messages to the user (e.g., instructions, errors, success/failure)
            const [message, setMessage] = useState('Point your camera at a drug\'s QR code.');
              // State to store the detailed verification data from the backend
                const [verificationData, setVerificationData] = useState(null);
                  // State to manage loading status during API calls
                    const [isLoading, setIsLoading] = useState(false);

                      // Define your backend API URL
                        // IMPORTANT: If your backend is running on a different port or domain, update this URL.
                          // For local development, if backend is on 5000 and frontend on 3000, this is correct.
                            const API_BASE_URL = 'http://localhost:5000/api';

                              // Function to handle successful QR code scans
                                const handleScan = async (data) => {
                                    if (data && !isLoading) { // Prevent multiple scans while an API call is in progress
                                          setScanResult(data); // Set the scanned data
                                                setMessage('Scanning complete. Verifying drug...');
                                                      setVerificationData(null); // Clear previous verification data
                                                            setIsLoading(true); // Set loading state

                                                                  try {
                                                                          const response = await fetch(`${API_BASE_URL}/verify-qr`, {
                                                                                    method: 'POST',
                                                                                              headers: {
                                                                                                          'Content-Type': 'application/json',
                                                                                                                    },
                                                                                                                              body: JSON.stringify({ qrCode: data }), // Send the scanned QR code data
                                                                                                                                      });

                                                                                                                                              const result = await response.json();

                                                                                                                                                      if (response.ok) { // Check if the HTTP status code is 2xx
                                                                                                                                                                setVerificationData(result.data); // Store the detailed drug data
                                                                                                                                                                          setMessage(result.message); // Display success message from backend
                                                                                                                                                                                  } else {
                                                                                                                                                                                            // Handle API errors (e.g., 404 Not Found, 500 Server Error)
                                                                                                                                                                                                      setMessage(`Verification failed: ${result.message || 'An unknown error occurred.'}`);
                                                                                                                                                                                                                setVerificationData(null);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                      console.error('Error during QR verification:', error);
                                                                                                                                                                                                                                              setMessage('Network error or server is unreachable. Please try again.');
                                                                                                                                                                                                                                                      setVerificationData(null);
                                                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                                                    setIsLoading(false); // Reset loading state
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                  // Function to handle errors during QR code scanning
                                                                                                                                                                                                                                                                                    const handleError = (err) => {
                                                                                                                                                                                                                                                                                        console.error(err);
                                                                                                                                                                                                                                                                                            setMessage('Error accessing camera. Please ensure camera permissions are granted and try refreshing the page. If in a sandboxed environment, camera access might be restricted.');
                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                // Effect to clear messages after a few seconds, or when scanResult changes
                                                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                                                      // Only clear message if it's not a loading or error message
                                                                                                                                                                                                                                                                                                          if (scanResult && !isLoading && !message.includes('Error') && !message.includes('failed')) {
                                                                                                                                                                                                                                                                                                                const timer = setTimeout(() => {
                                                                                                                                                                                                                                                                                                                        setMessage('Scan another QR code or refresh to start over.');
                                                                                                                                                                                                                                                                                                                              }, 7000); // Give more time for verification result to be read
                                                                                                                                                                                                                                                                                                                                    return () => clearTimeout(timer);
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          }, [scanResult, isLoading, message]); // Re-run when these states change

                                                                                                                                                                                                                                                                                                                                            // Function to toggle camera facing mode
                                                                                                                                                                                                                                                                                                                                              const toggleCamera = () => {
                                                                                                                                                                                                                                                                                                                                                  setFacingMode(prevMode => (prevMode === 'environment' ? 'user' : 'environment'));
                                                                                                                                                                                                                                                                                                                                                      setMessage(`Switched to ${facingMode === 'environment' ? 'front' : 'back'} camera.`);
                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                              <div className="min-h-screen bg-gradient-to-br from-green-50 to-blue-100 flex flex-col items-center justify-center p-4 font-inter">
                                                                                                                                                                                                                                                                                                                                                                    {/* Header Section */}
                                                                                                                                                                                                                                                                                                                                                                          <header className="w-full max-w-2xl text-center mb-8">
                                                                                                                                                                                                                                                                                                                                                                                  <h1 className="text-4xl font-extrabold text-green-700 mb-2 rounded-lg p-2 shadow-md bg-white">
                                                                                                                                                                                                                                                                                                                                                                                            MediVerify
                                                                                                                                                                                                                                                                                                                                                                                                    </h1>
                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-lg text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                      Authenticating Medicines, Ensuring Safety.
                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* QR Scanner Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="bg-white rounded-xl shadow-2xl p-6 w-full max-w-lg mb-8 border-b-4 border-green-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-2xl font-semibold text-gray-800 mb-4 text-center">Scan Drug QR Code</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="relative w-full aspect-video bg-gray-200 rounded-lg overflow-hidden mb-4 border-2 border-dashed border-gray-400 flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* QR Reader Component */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <QrReader
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onResult={(result, error) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!!result) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              handleScan(result?.text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!!error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          handleError(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                constraints={{ facingMode: facingMode }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            scanDelay={500} // Delay between scans to prevent multiple detections
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        videoContainerStyle={{ width: '100%', height: '100%', padding: '0px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    videoStyle={{ width: '100%', height: '100%', objectFit: 'cover' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Overlay for visual guidance */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-3/4 h-3/4 border-4 border-white opacity-75 rounded-lg"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Camera Toggle Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={toggleCamera}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full py-3 px-6 bg-blue-500 text-white font-bold rounded-lg shadow-md hover:bg-blue-600 transition duration-300 ease-in-out flex items-center justify-center space-x-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>Switch Camera ({facingMode === 'environment' ? 'Front' : 'Back'})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Results and Messages Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <section className="bg-white rounded-xl shadow-2xl p-6 w-full max-w-lg border-b-4 border-blue-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-semibold text-gray-800 mb-4 text-center">Verification Result</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="min-h-[80px] bg-gray-50 p-4 rounded-lg border border-gray-200 flex flex-col items-center justify-center text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {isLoading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-blue-600 font-medium">Verifying... Please wait.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : verificationData ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-left w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className={`text-lg font-bold mb-2 ${verificationData.status === 'authentic' ? 'text-green-600' : verificationData.status === 'counterfeit' ? 'text-red-600' : 'text-orange-600'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Status: {verificationData.status.toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-700"><strong>Drug Name:</strong> {verificationData.drugName}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-700"><strong>Manufacturer:</strong> {verificationData.manufacturer}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-700"><strong>Batch Number:</strong> {verificationData.batchNumber}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-700"><strong>Expiry Date:</strong> {verificationData.expiryDate}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-700 mt-2"><strong>Supply Chain:</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ul className="list-disc list-inside text-gray-600 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {verificationData.supplyChain.map((step, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li key={index}>{step}</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-700 mt-2"><strong>Description:</strong> {verificationData.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-500 italic">{message}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <footer className="mt-8 text-center text-gray-600 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>&copy; 2024 MediVerify. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                