// server.js - MediVerify Backend with AI Simulation

// Import necessary modules
const express = require('express');
const cors = require('cors');
const multer = require('multer'); // Middleware for handling multipart/form-data (file uploads)
const path = require('path');     // Node.js path module for handling file paths

// Initialize the Express application
const app = express();
const PORT = process.env.PORT || 5000;

// --- Middleware Setup ---
app.use(cors()); // Enable CORS for all routes
app.use(express.json()); // Enable Express to parse JSON bodies

// Configure Multer for file storage
// For this MVP, we'll store files in a 'uploads' directory.
// In a production app, you might use cloud storage (S3, GCS) or process directly in memory.
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
      // Create the 'uploads' directory if it doesn't exist
          const uploadDir = path.join(__dirname, 'uploads');
              // You might want to add a check here to ensure the directory exists
                  // fs.mkdirSync(uploadDir, { recursive: true });
                      cb(null, uploadDir);
                        },
                          filename: function (req, file, cb) {
                              // Generate a unique filename to prevent collisions
                                  cb(null, file.fieldname + '-' + Date.now() + path.extname(file.originalname));
                                    }
                                    });
                                    const upload = multer({ storage: storage });

                                    // --- Simulated Blockchain Ledger Data (from previous step) ---
                                    const blockchainLedger = [
                                      {
                                          qrCode: 'MEDIVERIFY-DRUG-ABC-12345',
                                              manufacturer: 'PharmaCorp International',
                                                  drugName: 'AntiMalaria Plus',
                                                      batchNumber: 'AM-2024-001',
                                                          expiryDate: '2026-12-31',
                                                              supplyChain: [
                                                                    'Factory: PharmaCorp HQ (India)',
                                                                          'Distributor: West Africa Pharma Hub (Lagos, Nigeria)',
                                                                                'Pharmacy: HealthFirst Pharmacy (Accra, Ghana)'
                                                                                    ],
                                                                                        status: 'authentic',
                                                                                            description: 'A broad-spectrum antimalarial medication.',
                                                                                              },
                                                                                                {
                                                                                                    qrCode: 'MEDIVERIFY-DRUG-XYZ-67890',
                                                                                                        manufacturer: 'Global Meds Ltd.',
                                                                                                            drugName: 'PainRelief Forte',
                                                                                                                batchNumber: 'PR-2024-005',
                                                                                                                    expiryDate: '2025-08-15',
                                                                                                                        supplyChain: [
                                                                                                                              'Factory: Global Meds (China)',
                                                                                                                                    'Distributor: AfriHealth Supplies (Abuja, Nigeria)',
                                                                                                                                          'Pharmacy: CityCare Pharmacy (Kumasi, Ghana)'
                                                                                                                                              ],
                                                                                                                                                  status: 'authentic',
                                                                                                                                                      description: 'Fast-acting pain relief for moderate to severe pain.',
                                                                                                                                                        },
                                                                                                                                                          {
                                                                                                                                                              qrCode: 'MEDIVERIFY-DRUG-FAKE-00000',
                                                                                                                                                                  manufacturer: 'Unknown',
                                                                                                                                                                      drugName: 'Counterfeit Cough Syrup',
                                                                                                                                                                          batchNumber: 'FAKE-2024-001',
                                                                                                                                                                              expiryDate: '2024-01-01',
                                                                                                                                                                                  supplyChain: [
                                                                                                                                                                                        'Unknown Origin',
                                                                                                                                                                                              'Illicit Distribution Network'
                                                                                                                                                                                                  ],
                                                                                                                                                                                                      status: 'counterfeit',
                                                                                                                                                                                                          description: 'This drug is suspected to be counterfeit. Exercise extreme caution.',
                                                                                                                                                                                                            },
                                                                                                                                                                                                              {
                                                                                                                                                                                                                  qrCode: 'MEDIVERIFY-DRUG-EXPIRED-11111',
                                                                                                                                                                                                                      manufacturer: 'SafeMeds Inc.',
                                                                                                                                                                                                                          drugName: 'Vitamin C 1000mg',
                                                                                                                                                                                                                              batchNumber: 'VC-2023-010',
                                                                                                                                                                                                                                  expiryDate: '2023-05-20',
                                                                                                                                                                                                                                      supplyChain: [
                                                                                                                                                                                                                                            'Factory: SafeMeds (USA)',
                                                                                                                                                                                                                                                  'Distributor: Local Health Distributors (Accra, Ghana)',
                                                                                                                                                                                                                                                        'Pharmacy: Community Drug Store (Lagos, Nigeria)'
                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                status: 'authentic (expired)',
                                                                                                                                                                                                                                                                    description: 'High-potency Vitamin C supplement. Note: This batch is authentic but has passed its expiry date.',
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                      ];

                                                                                                                                                                                                                                                                      // --- API Endpoint for QR Code Verification (from previous step) ---
                                                                                                                                                                                                                                                                      app.post('/api/verify-qr', (req, res) => {
                                                                                                                                                                                                                                                                        const { qrCode } = req.body;
                                                                                                                                                                                                                                                                          console.log(`Received QR code for verification: ${qrCode}`);

                                                                                                                                                                                                                                                                            const drugRecord = blockchainLedger.find(drug => drug.qrCode === qrCode);

                                                                                                                                                                                                                                                                              if (drugRecord) {
                                                                                                                                                                                                                                                                                  console.log(`Drug record found for ${qrCode}:`, drugRecord);
                                                                                                                                                                                                                                                                                      res.json({
                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                  message: 'Drug verified successfully!',
                                                                                                                                                                                                                                                                                                        data: drugRecord
                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                  console.log(`No record found for QR code: ${qrCode}`);
                                                                                                                                                                                                                                                                                                                      res.status(404).json({
                                                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                                  message: 'Drug not found or is counterfeit. Please check the QR code or report suspicious activity.',
                                                                                                                                                                                                                                                                                                                                        data: null
                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                              // --- NEW API Endpoint for AI Package Verification Simulation ---
                                                                                                                                                                                                                                                                                                                                              // 'upload.single('packageImage')' means it expects a single file upload
                                                                                                                                                                                                                                                                                                                                              // with the field name 'packageImage' from the frontend (matching formData.append('packageImage', ...)).
                                                                                                                                                                                                                                                                                                                                              app.post('/api/verify-package-ai', upload.single('packageImage'), (req, res) => {
                                                                                                                                                                                                                                                                                                                                                // Check if a file was uploaded
                                                                                                                                                                                                                                                                                                                                                  if (!req.file) {
                                                                                                                                                                                                                                                                                                                                                      return res.status(400).json({
                                                                                                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                                                                                                  message: 'No image file uploaded.',
                                                                                                                                                                                                                                                                                                                                                                        data: null
                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                console.log(`Received image for AI verification: ${req.file.filename}`);
                                                                                                                                                                                                                                                                                                                                                                                  // In a real application, you would now send `req.file.path` (the path to the uploaded image)
                                                                                                                                                                                                                                                                                                                                                                                    // to your AI model (e.g., a Python script running TensorFlow/OpenCV).
                                                                                                                                                                                                                                                                                                                                                                                      // The AI model would process the image and return a result.

                                                                                                                                                                                                                                                                                                                                                                                        // --- AI Simulation Logic ---
                                                                                                                                                                                                                                                                                                                                                                                          // For demonstration, we'll simulate AI results based on simple conditions or randomness.
                                                                                                                                                                                                                                                                                                                                                                                            // In a real scenario, this is where your trained computer vision model would run.
                                                                                                                                                                                                                                                                                                                                                                                              const simulatedResults = [
                                                                                                                                                                                                                                                                                                                                                                                                  { authenticity: 'authentic', confidence: 0.98, details: 'Packaging matches known genuine patterns. Logos and fonts appear correct.' },
                                                                                                                                                                                                                                                                                                                                                                                                      { authenticity: 'counterfeit', confidence: 0.85, details: 'Detected inconsistencies in packaging design, blurry text, or mismatched logos.' },
                                                                                                                                                                                                                                                                                                                                                                                                          { authenticity: 'authentic', confidence: 0.92, details: 'Minor wear and tear detected, but overall packaging characteristics align with genuine product.' },
                                                                                                                                                                                                                                                                                                                                                                                                              { authenticity: 'counterfeit', confidence: 0.70, details: 'Suspicious serialization or batch number format. Further investigation recommended.' },
                                                                                                                                                                                                                                                                                                                                                                                                                ];

                                                                                                                                                                                                                                                                                                                                                                                                                  // Pick a random simulated result for now
                                                                                                                                                                                                                                                                                                                                                                                                                    const randomResult = simulatedResults[Math.floor(Math.random() * simulatedResults.length)];

                                                                                                                                                                                                                                                                                                                                                                                                                      // Simulate a delay for AI processing
                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                  success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                        message: `AI package verification complete. Status: ${randomResult.authenticity.toUpperCase()}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                              data: randomResult
                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 1500); // Simulate 1.5 seconds of AI processing time
                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- Basic Root Route ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.get('/', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.send('MediVerify Backend is running! Access /api/verify-qr for QR verification and /api/verify-package-ai for AI package verification.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                      // --- Start the Server ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`MediVerify Backend server running on port ${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`Access it at http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                          